SUBROUTINE DUNAVANT_RULE_WRAPPER(RULE,ORDER,X,Y,W)
IMPLICIT NONE
INTEGER :: ORDER, RULE
INTEGER :: I
REAL(8), DIMENSION(2,ORDER) :: XY
REAL(8), DIMENSION(ORDER),INTENT(OUT) :: X, Y
REAL(8), DIMENSION(ORDER),INTENT(OUT) :: W
CALL DUNAVANT_RULE(RULE,ORDER,XY,W)
DO I=1, ORDER
    X(I) = XY(1, I)
    Y(I) = XY(2, I)
END DO
END SUBROUTINE DUNAVANT_RULE_WRAPPER